### ISSUE TITLE
Add a factorial program

### ISSUE THREAD

**Issue by divyanshugarg36** [divyanshugarg36/c-programs#25]

**Comment by killerkc12** [comment]
I like to work on this issue

**Comment by divyanshugarg36** [comment]
Go forward then :train:

**Comment by arsh939** [comment]
no, that's my job!

**Comment by killerkc12** [comment]
is it getting assigne me or not then?

**Comment by divyanshugarg36** [comment]
> no, that's my job!

No bro @killerkc12 asked first
dare to send a PR and i will simply mark it as invalid

**Comment by divyanshugarg36** [comment]
@killerkc12 Its yours go ahead

**Comment by arsh939** [comment]
ok :(

**Comment by killerkc12** [comment]
@divyanshugarg36 thank you
